### ISSUE TITLE
Problem with universal fixed points constraints in python

### ISSUE THREAD

**Issue by leonard9338** [bioasp/bonesis#1]
Hello,
I have been using bonesis for some time and recently in the last version a problem appeared in the python encoding of the universal fixed points constraints:

`jupyter nbconvert --execute --to HTML examples/Tutorial.ipynb`

```
 [NbConvertApp] Converting notebook examples/Tutorial.ipynb to HTML

[NbConvertApp] Executing notebook with kernel: python3
/tmp/bonesis_m6y30y2.lp:21:15-23: info: atom does not occur in any rule head:
  is_tp(X)

/tmp/bonesis_m6y30y2.lp:28:29-47: info: atom does not occur in any rule head:
  locked((pr,X,Y),N)

/tmp/bonesis_m6y30y2.lp:30:29-47: info: atom does not occur in any rule head:
  locked((pr,X,Y),N)

/tmp/bonesisv_c87iav.lp:21:15-23: info: atom does not occur in any rule head:
  is_tp(X)

/tmp/bonesisv_c87iav.lp:28:29-47: info: atom does not occur in any rule head:
  locked((pr,X,Y),N)

/tmp/bonesisv_c87iav.lp:30:29-47: info: atom does not occur in any rule head:
  locked((pr,X,Y),N)

Traceback (most recent call last):
  File "/home/herault/bin/miniconda3/envs/bonesis_local/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/exporters/html.py", line 119, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 369, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/herault/bin/miniconda3/envs/bonesis_local/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
bo.all_fixpoints({bo.obs(obs) for obs in ["fA", "fMS", "fT", "zero"]});
------------------

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-90ff4d124562> in <module>
----> 1 bo.all_fixpoints({bo.obs(obs) for obs in ["fA", "fMS", "fT", "zero"]});

<ipython-input-1-90ff4d124562> in <setcomp>(.0)
----> 1 bo.all_fixpoints({bo.obs(obs) for obs in ["fA", "fMS", "fT", "zero"]});

TypeError: unhashable type: 'ObservationVar'
TypeError: unhashable type: 'ObservationVar'
```

Could you help me please?

Léonard

**Comment by pauleve** [comment]
Thanks for the report, I'll work on a fix asap; in the meantime it should be enough to use lists instead of sets:
```py
bo.all_fixpoints([bo.obs(obs) for obs in ["fA", "fMS", "fT", "zero"]])
```
